export const WEATHER_SHOW_RESET = 'WEATHER_SHOW_RESET'
export const WEATHER_SHOW_SET_ERROR = 'WEATHER_SHOW_SET_ERROR'
export const WEATHER_SHOW_SET_RETRIEVED = 'WEATHER_SHOW_SET_RETRIEVED'
export const WEATHER_SHOW_TOGGLE_LOADING = 'WEATHER_SHOW_TOGGLE_LOADING'
export const WEATHER_SHOW_SET_GET_STATS = 'WEATHER_SHOW_SET_GET_STATS'
export const WEATHER_SHOW_SET_VIOLATIONS = 'WEATHER_SHOW_SET_VIOLATIONS'

