export const WEATHER_GET_DATA_RESET = 'WEATHER_GET_DATA_RESET'
export const WEATHER_GET_DATA_SET_ERROR = 'WEATHER_GET_DATA_SET_ERROR'
export const WEATHER_GET_DATA_TOGGLE_LOADING = 'WEATHER_GET_DATA_TOGGLE_LOADING'
export const WEATHER_GET_DATA_SET_GET_DATA = 'WEATHER_GET_DATA_SET_GET_DATA'
export const WEATHER_GET_DATA_SET_VIOLATIONS = 'WEATHER_GET_DATA_SET_VIOLATIONS'

